sudo: required
services:
  - docker
before_install:
  - docker build -t raghureddycloud/dockerpoc:v4.0 .
script:
  - echo "$password" | docker login -u "$username" --password-stdin
  - docker images
  - docker push raghureddycloud/dockerpoc:v4.0
notifications:
  email:
    recipients:
      - raghureddycloud@gmail.com
    on_success: always
    on_failure: always
